// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uepbpzkzmcnsqbhstuof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcGJwemt6bWNuc3FiaHN0dW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NDM2NjUsImV4cCI6MjA3NTQxOTY2NX0.pFg2oYHYWdALtsb-78w0-FuosXBpdVV3hDTrwXmyD8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});